# DAV 5400 Assignment 4

Using the Numpy package.

## Problem 1
Find the distinct/unique common items between two Numpy arrays.

My approach uses Numpy's unique method and Numpy's intersect1d method to find the intersection of the unique members of each array.
unique method takes a Numpy array as input, and returns the sorted unique elements of the array.
intersect1d method returns an array containing intersection (or overlap) of two 1 dimensional Numpy arrays.

Example of this approach:

    import numpy as np
    a1 = np.array([1,2,3,4,5,4,6,4,3])
    a2 = np.array([1,2,4,7,8,9,8,7,8,9])
    c = np.unique(a1) #np.array([1,2,3,4,5,6])
    d = np.unique(a2) #np.array([1,2,4,7,8,9])
    np.intersect1d(c,d) #np.array([1,2,4])


In [2]:
#import numpy package
import numpy as np

In [4]:
#initialize numpy arrays.
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

#return intersection of unique values of the arrays.
np.intersect1d(np.unique(a), np.unique(b))

array([2, 4])

# Problem 2
Create a 5 x 3 array that looks like this:
<br>

    | 1 | 6 | 11 |
    | 2 | 7 | 12 |
    | 3 | 8 | 13 |
    | 4 | 9 | 14 |
    | 5 | 10 | 15 |
    
First, I used Numpy's arange method to generate a 1 dimensional array, with all the numbers from 1 to 16 (excluding 16). <br>
Then, I used Numpy's reshape method to reshape the 1 dimensional array into a 3 x 5 array.<br>
Finally, I used Numpy's T method to transpose the 3 x 5 array to a 5 x 3 array. 

In [6]:
#Make 5 x 3 array of numbers from 1 to 15, sorted by column.
np.arange(1,16).reshape(3,5).T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

## Problem 3
Remove elements from first array that are also present in second array.<br>
My approach uses Numpy's setdiff1d method to find the difference between the two sets. <br>
The difference between two sets returns the elements that are only present in the first set (or those that are not also found in the second set).

In [9]:
# initialize the arrays.
c = np.array([12, 5, 7, 15, 3, 1, 8])
d = np.array([14, 6, 3, 11, 19, 12, 5])

#set c to be the difference between the two arrays.
c = np.setdiff1d(c,d)

#return c, showing the difference between the arrays.
c

array([ 1,  7,  8, 15])

## Problem 4
Create a Numpy array to show the cumulative miles recorded on a trip between NYC to Key West (1549 miles). <br>
Convert that array to show the total miles rode per day of the trip. <br>
My approach was to create two functions, bike_ride_odometer and bike_ride_daily, to create Numpy arrays holding the odometer readings and daily miles of the trip. <br>
The bike_ride_odometer function takes the total distance travelled, an array containing distances that could have been travelled in 1 day, the total number of days on the trip, and the total number of rest_days on the trip. <br>
I used the Numpy empty method to create an empty array of size total days to hold the odometer readings. <br>
I then loop through and generate odometer readings until the constraints are met, that the total distance was travelled and that the number of rest days was met. <br>
I loop through the number of days, and then choose a number between 0 and 4 using Numpy's randint method of the random library. <br>
If the number is zero, and it's not the first day, and I haven't rested the amount I'm allowed to, and I didn't rest yesterday, than the distance travelled today is zero (ie. I rested). <br>
Otherwise, the distance travelled today is obtained using Numpy's choice method of the random library to pick 1 random value from the per_day array, replace that value (so it can picked again), and  the item method is called to get just the item (as opposed to an array value). <br>
If it's not the first day, than the odometer reading is yesterday's odometer reading plus today's distance. Otherwise, if it's the first day, the odometer reading is the daily distance. <br>
When an array meeting all the constraints is generated, it is returned, breaking out of the loop to generate the array. <br>

The second function I used is the bike_ride_daily function to convert the odometer reading to daily bike ride readings. <br>
The input to the function is an array of odometer readings, and it returns an array of daily mileage.<br>
It loops through the indeces of the odometer readings, and sets the daily reading to be today's odometer reading minus yesterday's odometer reading. <br>

After creating the two functions, I created an array of average_bike_daily distances using Numpy's arange function to create an array of integers between 40 and 61 (excluding 61, so 40 to 60). <br>
I then called my two functions, and finally looped through the indeces in my daily_array and printed the day, daily_mileage, and odometer readings for each day.


In [27]:
def bike_ride_odometer(total_distance, per_day, days, rest_days):
    '''
    The bike_ride_odometer function takes 4 parameters, the total distance biked, 
    an array of bike distances per day, 
    the number of days of the trip, and the number of rest days on the trip,
    and returns an array of odometer readings for the trip meeting those constraints.
    
    Parameters: 
    total_distance: The integer value of total distance of the journey.
    per_day: An array (or list) containing the potential daily distances, from which to generate odometer readings.
    days: An integer value of the number of days of the trip.
    rest_days: An integer value of the number of day on the trip that no distance was covered.
    
    Return:
    An array containing odometer readings for the trip, with the last value of the array being the total_distance,
    the length of the array being the days of the trip, and with the number of rest_days inputted.
    '''
    odometer = np.empty([days]) #initialize an empty array to contain odometer readings for the trip.
    zeroes = 0 #intialize the zeroes variable to represent rest days.
    
    # while loop to loop through until the constraints are met.
    # constraints are that last value in odometer must be total_distance
    # and number of rest days must be rest_days
    while not (odometer[days-1] == total_distance and zeroes == rest_days):
        # loop through the days
        for i in range(days):
            # take a random number between 0 and 4. 
            # if number is zero, and not on the first day, and you have rested less than
            # the number of rest_days and you didn't just rest.
            if np.random.randint(4) == 0 and i > 0 and zeroes < rest_days and odometer[i-1] > odometer[i-2]:
                # set x = 0 and add 1 to the zeroes (number of rest days)
                x = 0
                zeroes += 1
            else:
                #set x to be a random value from the per_day array.
                x = np.random.choice(per_day,1, replace = True).item()
            # if not on day 1.
            if i > 0:
                # The current odometer reading, is the previous odometer reading 
                #plus the distance travelled today.
                odometer[i] = odometer[i-1] + x
            # if it is day zero.
            if i == 0:
                # the odometer reading is the day's distance.
                odometer[i] = x
        # if the last day's reading is the total_distance and the zeroes is the number of rest_days
        if odometer[days-1] == total_distance and zeroes == rest_days:
            #return the odometer array
            return odometer
        else:
            #reset the zeroes variable, and try and generate the odometer array to meet the constraints..
            zeroes = 0
            
def bike_ride_daily(odometer):
    '''
    The bike_ride_daily function converts the daily readings from an odometer to be daily distances travelled.
    Parameters:
    odometer: An array of odometer readings from a bicycle trip.
    Return:
    An array of daily distances travelled.
    '''
    # initialize an empty array 
    daily = np.empty(len(odometer))
    # loop throguh indeces in odometer array.
    for i in range(len(odometer)):
        # if not on the first day
        if i > 0:
            # set daily distance to be today's odometer reading minus yesterday's reading.
            daily[i] = odometer[i] - odometer[i-1]
        else:
            # set today's distance to be today's odometer reading. 
            daily[i] = odometer[i]
    # return the daily array (containing daily distances.)
    return daily

# create the average_bike_per_day array to hold all integer values between 40 and 60
# as the average miles per day biked is 40-60.
average_bike_per_day = np.arange(40,61)

# Set variable nyc_to_key_west_odometer to be return from bike_ride_odometer function
# when distance travelled is 1549 miles, the per_day distances should come from the average_bike_per_day array
# the total number of days is 35 and there were 4 rest days.
nyc_to_key_west_odometer = bike_ride_odometer(1549,average_bike_per_day,35,4)

#Set variable nyc_to_key_west_per_day to be return of bike_ride_daily function
# with input nyc_to_key_west_odometer.
nyc_to_key_west_per_day = bike_ride_daily(nyc_to_key_west_odometer)

# loop through the indeces in the nyc_to_key_per_day array
for i in range(len(nyc_to_key_west_per_day)):
    # print the day, bike miles rode, and odometer reading using format strings.
    print("Day {}: Bike Miles Rode: {} Odometer Reading: {}".format(i+1, int(nyc_to_key_west_per_day[i]), int(nyc_to_key_west_odometer[i])))

Day 1: Bike Miles Rode: 60 Odometer Reading: 60
Day 2: Bike Miles Rode: 45 Odometer Reading: 105
Day 3: Bike Miles Rode: 42 Odometer Reading: 147
Day 4: Bike Miles Rode: 49 Odometer Reading: 196
Day 5: Bike Miles Rode: 42 Odometer Reading: 238
Day 6: Bike Miles Rode: 0 Odometer Reading: 238
Day 7: Bike Miles Rode: 58 Odometer Reading: 296
Day 8: Bike Miles Rode: 43 Odometer Reading: 339
Day 9: Bike Miles Rode: 56 Odometer Reading: 395
Day 10: Bike Miles Rode: 60 Odometer Reading: 455
Day 11: Bike Miles Rode: 0 Odometer Reading: 455
Day 12: Bike Miles Rode: 59 Odometer Reading: 514
Day 13: Bike Miles Rode: 0 Odometer Reading: 514
Day 14: Bike Miles Rode: 59 Odometer Reading: 573
Day 15: Bike Miles Rode: 57 Odometer Reading: 630
Day 16: Bike Miles Rode: 48 Odometer Reading: 678
Day 17: Bike Miles Rode: 46 Odometer Reading: 724
Day 18: Bike Miles Rode: 53 Odometer Reading: 777
Day 19: Bike Miles Rode: 43 Odometer Reading: 820
Day 20: Bike Miles Rode: 40 Odometer Reading: 860
Day 21: Bike 

## Problem 5
Using data loaded into a Numpy array representing NYC Water Consumption obtained from 
https://data.cityofnewyork.us/Environment/Water-Consumption-In-The-New-York-City/ia2d-e54m, use Numpy functionality to answer some questions about the data.

In [28]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


numpy.ndarray

### Question 1
What is the maximum yearly NYC consumption of water in millions of gallons per day? <br>
The third column of the array has the NYC consumption of water in millions of gallons per day. <br>
So I sliced the nyc_water array to get the third column, and called Numpy's max method on the slice, to find the maximum value. <br>

In [29]:
# Max value of third column of nyc_water array.
nyc_water[:, 2].max()

1512.0

### Question 2
How many calendar years are represented within this data set? <br>
I used Numpy's shape method to get the number of rows and columns in the data set.<br>
I wanted only the row value, so I used subscript zero, to get the first value. <br>
The number of rows corresponds to the number of years in the dataset, as each year is its own row."

In [30]:
# Number of rows in nyc_water array.
np.shape(nyc_water)[0]

39

### Question 3
What is the mean and the standard deviation of the per capita daily water consumption? <br>
The fourth column of the array has the per capita daily water consumption. <br>
I sliced the nyc_water array to get the fourth column, and then called the mean method on the slice. <br>
I then called the std method on the slice to get the standard deviation of per capita daily water consumption. <br>


In [31]:
# Mean of the fourth column of nyc_water array.
nyc_water[:,3].mean()

160.30769230769232

In [32]:
# Standard deviation of the fourth column of the nyc_water array.
nyc_water[:,3].std()

31.51894330370624

### Question 4
What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen <br>
Since the population is stored in the second column, I called Numpy's diff function on a slice of nyc_water array containing the second column. <br>
I set that result to the pop_diff variable, and print the pop_diff variable

In [33]:
# Set pop_diff to equal result of Numpy's diff function called on second column of nyc_water.
pop_diff = np.diff(nyc_water[:,1])

# print the pop_diff array.
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
